name: sentry
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  ffi: ^2.0.1
  flutter_rust_bridge: ^1.41.2
  freezed_annotation: ^2.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  ffigen: ^6.1.2
  build_runner: ^2.2.0
  freezed: ^2.1.0+1

flutter:
  uses-material-design: false