[package]
name = "native"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["lib", "rlib", "staticlib", "cdylib"]

[dependencies]
flutter_rust_bridge = "1"
anyhow = "1"

[profile.release]
lto = true
codegen-units = 1